// import hihi from "./imag/chola.jpg";

const Menu =[
    {
        id: 1,
        name: "maggi",
        category: "Snacks",
        image: "./imag/chola.jpg",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 2,
        name: "allupakoda",
        category: "Breakfast",
        image: "react_n\public\images\vegthali.jpg",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 3,
        name: "chola",
        category: "Breakfast",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 4,
        name: "momos",
        category: "Snacks",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 5,
        name: "nonvegthali",
        category: "Lunch",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 6,
        name: "pavbhaji",
        category: "Breakfast",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 7,
        name: "pizza",
        category: "Dinner",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 8,
        name: "puri",
        category: "Lunch",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 9,
        name: "rajmarice",
        category: "Dinner",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 10,
        name: "rotiwithmeat",
        category: "Lunch",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 11,
        name: "samomsa",
        category: "Snacks",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 12,
        name: "sweet",
        category: "Dinner",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 13,
        name: "vegthali",
        category: "Lunch",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxuf7r fbfyufyubff tfvb jv brexcyvuhvgv n cg  gn vgn v vvhv h vv v ebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 14,
        name: "Egg Maggi",
        category: "midnight",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxuf7r fbfyufyubff tfvb jv brexcyvuhvgv n cg  gn vgn v vvhv h vv v ebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
    {
        id: 15,
        name: "bread chese",
        category: "midnight",
        image: " wedewdew",
        description: "loremefedbdeibduie ceubcuyfbeuxeux efxuf7r fbfyufyubff tfvb jv brexcyvuhvgv n cg  gn vgn v vvhv h vv v ebyufbeyub deyub xyubf dbfxdyub yub dxyuvxyudyudfyuxb eux ebfx dyu xbv xyu xyu",
        price: 25,
    },
]
export default Menu;